### PR TITLE
Limit number of parallel requests when downloading collections

### LINKED ISSUE #236: XST can not download large document/collection sets
### What happened?

When downloading a collection with a lot of resources (documents, collections recursively), xst stops after 3000+ files.

eg
```
Γ£ÿ AA.xml could not be created! Reason: connect ENOBUFS 1.2.3.4:8080 - Local (undefined:undefined)
Γ£ÿ BB.xml could not be created! Reason: connect ENOBUFS 1.2.3.4:8080 - Local (undefined:undefined)
Γ£ÿ CC.xml could not be created! Reason: connect ENOBUFS 1.2.3.4:8080 - Local (undefined:undefined)
```

the process stops with

```
Γ£ÿ c5b327080fd4d751bbc4d19160dc8a49.xsd could not be created! Reason: aborted
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: aborted
    at Socket.socketCloseListener (node:_http_client:460:19)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:338:12) {
  code: 'ECONNRESET'
}

Node.js v20.14.0
```

### System Information

```sh
Build: eXist-6.2.0 (c8fa4958b6d4a50bd0cba7f3e76a150226414187)
Java: 1.8.0_275 (Red Hat, Inc.)
OS: Linux 2.6.32-754.50.1.el6.x86_64 (amd64)
```

### Relevant shell output

```sh
Γ£ÿ c5b327080fd4d751bbc4d19160dc8a49.xsd could not be created! Reason: aborted
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: aborted
    at Socket.socketCloseListener (node:_http_client:460:19)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:338:12) {
  code: 'ECONNRESET'
```

### PR DESCRIPTION
**Pull request by DrRataplan**
Downloading large collections caused an unpredictable amount of requests to run in parallel. The new limit makes download requests not to run in parallel.

Also use Promise.all / correct awaits for promises in general.

Reused the current tests to cover the new code.

closes #236

### CODE REVIEW

File: commands/get.js [hunk 1]
```diff
@@ -301,6 +356,11 @@ export function builder (yargs) {
       type: 'boolean',
       default: false
     })
+    .option('max-inflight-requests', {
+      describe: 'How many download resource can be downloaded at the same time',
+      type: 'number',
+      default: 10
```
Comment (line-o) [inline commands/get.js:362]: The name of the option is hard to explain. Please align up- and download options.

File: commands/get.js [hunk 2]
```diff
@@ -115,13 +159,14 @@ async function downloadResource (db, options, resource, directory, collection, r
...
  * @param {NodeExist} db NodeExist client
+ * @param {GetOptions} options
  * @param {boolean} verbose
  * @param {String} collection
  * @param {String} baseCollection
  */
 async function downloadCollection (db, options, collection, baseCollection, directory) {
   const absCollection = posix.join(baseCollection, collection)
-  const { verbose } = options
+  const { verbose, maxInflightRequests = 10 } = options
```
Comment (line-o) [inline commands/get.js:169]: The default value for parallel requests is already set further up when parsing command line options. It can be removed here

File: commands/get.js [hunk 3]
```diff
@@ -1,6 +1,51 @@
...
-import { writeFileSync, statSync, existsSync, mkdirSync } from 'node:fs'
+import { statSync, existsSync, mkdirSync } from 'node:fs'
 import { connect } from '@existdb/node-exist'
+import { writeFile } from 'node:fs/promises'
+
+let inflightPromises = 0
+
+const queue = []
+
+async function handleNextInQueue () {
```
Comment (line-o) [inline commands/get.js:10]: Consider aligning with the solution in download command.

Either remove the dependency on Bottleneck entirely or use it here as well

**Review by line-o — CHANGES_REQUESTED** [review]
Thanks for taking this on. Unfortunately, we hadn't had the chance to coordinate first. Let me know if you have questions to my points.

File: commands/get.js [hunk 4]
```diff
@@ -189,12 +245,13 @@ async function getPathInfo (db, path) {
  */
 async function downloadCollectionOrResource (db, source, target, options) {
   // read parameters
-//  const start = Date.now()
+  //  const start = Date.now()
   const root = resolve(target)
 
   if (options.verbose) {
```
[the remark this answers is not in the document]
Comment (line-o) [reply commands/get.js:207]: Actually only the server part should be removed. And this can happen in a separate PR.

**Review by line-o — COMMENTED** [review]
should be good to go now

**Comment by line-o** [comment]
failing tests on latest are unrelated and caused by a bug in exist-db ( see https://github.com/eXist-db/exist/pull/5816)

**Review by line-o — APPROVED** [review]
Ready to merge
